// component provider file
export {default as Hero} from './Hero'
export {default as HeroCarousel} from './HeroCarousel'
export {default as Staking} from './Staking'
export {default as ExclusiveNFTS} from './ExclusiveNFTS'
export {default as Features} from './Features'
export {default as Gameplay} from './Gameplay'
export {default as HowItWork} from './HowItWork'
export {default as Benefit} from './Benefit'
export {default as Mission} from './Mission'
export {default as Faqs} from './Faqs'
export {default as Vision} from './Vision'
export {default as Tokenomics} from './Tokenomics'
export {default as Roadmap} from './Roadmap'
export {default as Protected} from './Protected'
export {default as Friends} from './Friends'
export {default as GoingLive} from './GoingLive'